attention_head_size: 1
categorical_groups: {}
causal_attention: true
dataset_parameters:
  add_encoder_length: false
  add_relative_time_idx: false
  add_target_scales: false
  allow_missing_timesteps: true
  categorical_encoders:
    __group_id__symbol_id: !!python/object:pytorch_forecasting.data.encoders.NaNLabelEncoder
      add_nan: false
      classes_:
        '0': 0
        '1': 1
        '10': 2
        '11': 3
        '12': 4
        '13': 5
        '14': 6
        '15': 7
        '16': 8
        '17': 9
        '18': 10
        '19': 11
        '2': 12
        '20': 13
        '21': 14
        '22': 15
        '23': 16
        '24': 17
        '25': 18
        '26': 19
        '27': 20
        '28': 21
        '29': 22
        '3': 23
        '30': 24
        '31': 25
        '32': 26
        '33': 27
        '34': 28
        '35': 29
        '36': 30
        '37': 31
        '38': 32
        '4': 33
        '5': 34
        '6': 35
        '7': 36
        '8': 37
        '9': 38
      classes_vector_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - &id001 !!python/name:numpy.ndarray ''
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 39
        - !!python/object/apply:numpy.dtype
          args:
          - U2
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - 8
          - 4
          - 8
        - false
        - !!binary |
          MAAAAAAAAAAxAAAAAAAAADEAAAAwAAAAMQAAADEAAAAxAAAAMgAAADEAAAAzAAAAMQAAADQAAAAx
          AAAANQAAADEAAAA2AAAAMQAAADcAAAAxAAAAOAAAADEAAAA5AAAAMgAAAAAAAAAyAAAAMAAAADIA
          AAAxAAAAMgAAADIAAAAyAAAAMwAAADIAAAA0AAAAMgAAADUAAAAyAAAANgAAADIAAAA3AAAAMgAA
          ADgAAAAyAAAAOQAAADMAAAAAAAAAMwAAADAAAAAzAAAAMQAAADMAAAAyAAAAMwAAADMAAAAzAAAA
          NAAAADMAAAA1AAAAMwAAADYAAAAzAAAANwAAADMAAAA4AAAANAAAAAAAAAA1AAAAAAAAADYAAAAA
          AAAANwAAAAAAAAA4AAAAAAAAADkAAAAAAAAA
      warn: true
    symbol_id: !!python/object:pytorch_forecasting.data.encoders.NaNLabelEncoder
      add_nan: true
      classes_: &id004
        '0': 1
        '1': 2
        '10': 3
        '11': 4
        '12': 5
        '13': 6
        '14': 7
        '15': 8
        '16': 9
        '17': 10
        '18': 11
        '19': 12
        '2': 13
        '20': 14
        '21': 15
        '22': 16
        '23': 17
        '24': 18
        '25': 19
        '26': 20
        '27': 21
        '28': 22
        '29': 23
        '3': 24
        '30': 25
        '31': 26
        '32': 27
        '33': 28
        '34': 29
        '35': 30
        '36': 31
        '37': 32
        '38': 33
        '4': 34
        '5': 35
        '6': 36
        '7': 37
        '8': 38
        '9': 39
        nan: 0
      classes_vector_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 40
        - !!python/object/apply:numpy.dtype
          args:
          - U3
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - 12
          - 4
          - 8
        - false
        - !!binary |
          bgAAAGEAAABuAAAAMAAAAAAAAAAAAAAAMQAAAAAAAAAAAAAAMQAAADAAAAAAAAAAMQAAADEAAAAA
          AAAAMQAAADIAAAAAAAAAMQAAADMAAAAAAAAAMQAAADQAAAAAAAAAMQAAADUAAAAAAAAAMQAAADYA
          AAAAAAAAMQAAADcAAAAAAAAAMQAAADgAAAAAAAAAMQAAADkAAAAAAAAAMgAAAAAAAAAAAAAAMgAA
          ADAAAAAAAAAAMgAAADEAAAAAAAAAMgAAADIAAAAAAAAAMgAAADMAAAAAAAAAMgAAADQAAAAAAAAA
          MgAAADUAAAAAAAAAMgAAADYAAAAAAAAAMgAAADcAAAAAAAAAMgAAADgAAAAAAAAAMgAAADkAAAAA
          AAAAMwAAAAAAAAAAAAAAMwAAADAAAAAAAAAAMwAAADEAAAAAAAAAMwAAADIAAAAAAAAAMwAAADMA
          AAAAAAAAMwAAADQAAAAAAAAAMwAAADUAAAAAAAAAMwAAADYAAAAAAAAAMwAAADcAAAAAAAAAMwAA
          ADgAAAAAAAAANAAAAAAAAAAAAAAANQAAAAAAAAAAAAAANgAAAAAAAAAAAAAANwAAAAAAAAAAAAAA
          OAAAAAAAAAAAAAAAOQAAAAAAAAAAAAAA
      warn: true
  constant_fill_strategy: null
  group_ids:
  - symbol_id
  lags: null
  max_encoder_length: 64
  max_prediction_length: 1
  min_encoder_length: 64
  min_prediction_idx: !!python/object/apply:numpy._core.multiarray.scalar
  - &id003 !!python/object/apply:numpy.dtype
    args:
    - i8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    gOgFAAAAAAA=
  min_prediction_length: 1
  predict_mode: false
  randomize_length: null
  scalers:
    PC1: null
    PC10: null
    PC100: null
    PC11: null
    PC12: null
    PC13: null
    PC14: null
    PC15: null
    PC16: null
    PC17: null
    PC18: null
    PC19: null
    PC2: null
    PC20: null
    PC21: null
    PC22: null
    PC23: null
    PC24: null
    PC25: null
    PC26: null
    PC27: null
    PC28: null
    PC29: null
    PC3: null
    PC30: null
    PC31: null
    PC32: null
    PC33: null
    PC34: null
    PC35: null
    PC36: null
    PC37: null
    PC38: null
    PC39: null
    PC4: null
    PC40: null
    PC41: null
    PC42: null
    PC43: null
    PC44: null
    PC45: null
    PC46: null
    PC47: null
    PC48: null
    PC49: null
    PC5: null
    PC50: null
    PC51: null
    PC52: null
    PC53: null
    PC54: null
    PC55: null
    PC56: null
    PC57: null
    PC58: null
    PC59: null
    PC6: null
    PC60: null
    PC61: null
    PC62: null
    PC63: null
    PC64: null
    PC65: null
    PC66: null
    PC67: null
    PC68: null
    PC69: null
    PC7: null
    PC70: null
    PC71: null
    PC72: null
    PC73: null
    PC74: null
    PC75: null
    PC76: null
    PC77: null
    PC78: null
    PC79: null
    PC8: null
    PC80: null
    PC81: null
    PC82: null
    PC83: null
    PC84: null
    PC85: null
    PC86: null
    PC87: null
    PC88: null
    PC89: null
    PC9: null
    PC90: null
    PC91: null
    PC92: null
    PC93: null
    PC94: null
    PC95: null
    PC96: null
    PC97: null
    PC98: null
    PC99: null
  static_categoricals:
  - symbol_id
  static_reals: null
  target: responder_6
  target_normalizer: &id005 !!python/object:pytorch_forecasting.data.encoders.GroupNormalizer
    _groups:
    - symbol_id
    _method_kwargs: {}
    center: true
    groups:
    - symbol_id
    method: standard
    method_kwargs: {}
    missing_:
      center: 1.4648914657300338e-05
      scale: 0.7965054512023926
    norm_: !!python/object:pandas.core.frame.DataFrame
      _flags:
        allows_duplicate_labels: true
      _metadata: []
      _mgr: !!python/object/apply:pandas.core.internals.managers.BlockManager
      - !!python/tuple
        - !!python/object/apply:pandas._libs.internals._unpickle_block
          - !!python/object/apply:numpy._core.multiarray._reconstruct
            args:
            - *id001
            - !!python/tuple
              - 0
            - !!binary |
              Yg==
            state: !!python/tuple
            - 1
            - !!python/tuple
              - 2
              - 39
            - !!python/object/apply:numpy.dtype
              args:
              - f4
              - false
              - true
              state: !!python/tuple
              - 3
              - <
              - null
              - null
              - null
              - -1
              - -1
              - 0
            - false
            - !!binary |
              5TuHutY97bvDDhM8trAbPA6eQzs1HJu8aWcAuu9TozzYzK+70FccOkePwjyPpEY8PlcMuy5abjvq
              oVI8Ci7Ru3k8c7o3Aj68R+j5ugnsFTzhC5o8U3uUO3hGjbxiHkY8dk8ZvTgZ2Lt1+sg7Q2WavMRx
              Mj2cxHU3sKKXO01GYzxAUZ28buO4Ozm1nDuuNzu6O+qnuyqtF7wwaIu9WpUdPzeXLz81fxo/mvgi
              P7kBOz9Way8/uaFyPx3PeT8TXB0/ihEsPw4GWT+H4B4/yOdLPzRnZT+W3oA/sRxAPxEpUT/WmXM/
              xyduP/q+gT9dsEc//8dMPyKIfT87bEU/LSlYP0MPZD+ZAVk/GXgsP3zmRz/BpzA/X2lYP1Gefj8x
              lh0/kFRmP/q/QT+SSXQ/Z1IcPxs8KD+H8lM/
          - !!python/object/apply:builtins.slice
            - 0
            - 2
            - 1
          - 2
      - - !!python/object/apply:pandas.core.indexes.base._new_Index
          - &id002 !!python/name:pandas.core.indexes.base.Index ''
          - data: !!python/object/apply:numpy._core.multiarray._reconstruct
              args:
              - *id001
              - !!python/tuple
                - 0
              - !!binary |
                Yg==
              state: !!python/tuple
              - 1
              - !!python/tuple
                - 2
              - !!python/object/apply:numpy.dtype
                args:
                - O8
                - false
                - true
                state: !!python/tuple
                - 3
                - '|'
                - null
                - null
                - null
                - -1
                - -1
                - 63
              - false
              - - center
                - scale
            name: null
        - !!python/object/apply:pandas.core.indexes.base._new_Index
          - *id002
          - data: !!python/object/apply:numpy._core.multiarray._reconstruct
              args:
              - *id001
              - !!python/tuple
                - 0
              - !!binary |
                Yg==
              state: !!python/tuple
              - 1
              - !!python/tuple
                - 39
              - *id003
              - false
              - !!binary |
                AQAAAAAAAAACAAAAAAAAAAMAAAAAAAAABAAAAAAAAAAFAAAAAAAAAAYAAAAAAAAABwAAAAAAAAAI
                AAAAAAAAAAkAAAAAAAAACgAAAAAAAAALAAAAAAAAAAwAAAAAAAAADQAAAAAAAAAOAAAAAAAAAA8A
                AAAAAAAAEAAAAAAAAAARAAAAAAAAABIAAAAAAAAAEwAAAAAAAAAUAAAAAAAAABUAAAAAAAAAFgAA
                AAAAAAAXAAAAAAAAABgAAAAAAAAAGQAAAAAAAAAaAAAAAAAAABsAAAAAAAAAHAAAAAAAAAAdAAAA
                AAAAAB4AAAAAAAAAHwAAAAAAAAAgAAAAAAAAACEAAAAAAAAAIgAAAAAAAAAjAAAAAAAAACQAAAAA
                AAAAJQAAAAAAAAAmAAAAAAAAACcAAAAAAAAA
            name: symbol_id
      _typ: dataframe
      attrs: {}
    scale_by_group: false
    transformation: null
  time_idx: time_idx
  time_varying_known_categoricals: null
  time_varying_known_reals:
  - PC1
  - PC2
  - PC3
  - PC4
  - PC5
  - PC6
  - PC7
  - PC8
  - PC9
  - PC10
  - PC11
  - PC12
  - PC13
  - PC14
  - PC15
  - PC16
  - PC17
  - PC18
  - PC19
  - PC20
  - PC21
  - PC22
  - PC23
  - PC24
  - PC25
  - PC26
  - PC27
  - PC28
  - PC29
  - PC30
  - PC31
  - PC32
  - PC33
  - PC34
  - PC35
  - PC36
  - PC37
  - PC38
  - PC39
  - PC40
  - PC41
  - PC42
  - PC43
  - PC44
  - PC45
  - PC46
  - PC47
  - PC48
  - PC49
  - PC50
  - PC51
  - PC52
  - PC53
  - PC54
  - PC55
  - PC56
  - PC57
  - PC58
  - PC59
  - PC60
  - PC61
  - PC62
  - PC63
  - PC64
  - PC65
  - PC66
  - PC67
  - PC68
  - PC69
  - PC70
  - PC71
  - PC72
  - PC73
  - PC74
  - PC75
  - PC76
  - PC77
  - PC78
  - PC79
  - PC80
  - PC81
  - PC82
  - PC83
  - PC84
  - PC85
  - PC86
  - PC87
  - PC88
  - PC89
  - PC90
  - PC91
  - PC92
  - PC93
  - PC94
  - PC95
  - PC96
  - PC97
  - PC98
  - PC99
  - PC100
  time_varying_unknown_categoricals: null
  time_varying_unknown_reals: null
  variable_groups: null
  weight: weight
dropout: 0.2
embedding_labels:
  symbol_id: *id004
embedding_paddings:
- symbol_id
embedding_sizes:
  symbol_id: !!python/tuple
  - 40
  - 13
hidden_continuous_size: 16
hidden_continuous_sizes: {}
hidden_size: 32
learning_rate: 0.005
log_gradient_flow: false
log_interval: -1
log_val_interval: null
lstm_layers: 1
mask_bias: -1000000000.0
max_encoder_length: 64
monotone_constaints: {}
monotone_constraints: {}
optimizer: adamw
optimizer_params: null
output_size: 1
output_transformer: *id005
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 1
reduce_on_plateau_reduction: 2.0
share_single_variable_networks: false
static_categoricals:
- symbol_id
static_reals: []
time_varying_categoricals_decoder: []
time_varying_categoricals_encoder: []
time_varying_reals_decoder:
- PC1
- PC2
- PC3
- PC4
- PC5
- PC6
- PC7
- PC8
- PC9
- PC10
- PC11
- PC12
- PC13
- PC14
- PC15
- PC16
- PC17
- PC18
- PC19
- PC20
- PC21
- PC22
- PC23
- PC24
- PC25
- PC26
- PC27
- PC28
- PC29
- PC30
- PC31
- PC32
- PC33
- PC34
- PC35
- PC36
- PC37
- PC38
- PC39
- PC40
- PC41
- PC42
- PC43
- PC44
- PC45
- PC46
- PC47
- PC48
- PC49
- PC50
- PC51
- PC52
- PC53
- PC54
- PC55
- PC56
- PC57
- PC58
- PC59
- PC60
- PC61
- PC62
- PC63
- PC64
- PC65
- PC66
- PC67
- PC68
- PC69
- PC70
- PC71
- PC72
- PC73
- PC74
- PC75
- PC76
- PC77
- PC78
- PC79
- PC80
- PC81
- PC82
- PC83
- PC84
- PC85
- PC86
- PC87
- PC88
- PC89
- PC90
- PC91
- PC92
- PC93
- PC94
- PC95
- PC96
- PC97
- PC98
- PC99
- PC100
time_varying_reals_encoder:
- PC1
- PC2
- PC3
- PC4
- PC5
- PC6
- PC7
- PC8
- PC9
- PC10
- PC11
- PC12
- PC13
- PC14
- PC15
- PC16
- PC17
- PC18
- PC19
- PC20
- PC21
- PC22
- PC23
- PC24
- PC25
- PC26
- PC27
- PC28
- PC29
- PC30
- PC31
- PC32
- PC33
- PC34
- PC35
- PC36
- PC37
- PC38
- PC39
- PC40
- PC41
- PC42
- PC43
- PC44
- PC45
- PC46
- PC47
- PC48
- PC49
- PC50
- PC51
- PC52
- PC53
- PC54
- PC55
- PC56
- PC57
- PC58
- PC59
- PC60
- PC61
- PC62
- PC63
- PC64
- PC65
- PC66
- PC67
- PC68
- PC69
- PC70
- PC71
- PC72
- PC73
- PC74
- PC75
- PC76
- PC77
- PC78
- PC79
- PC80
- PC81
- PC82
- PC83
- PC84
- PC85
- PC86
- PC87
- PC88
- PC89
- PC90
- PC91
- PC92
- PC93
- PC94
- PC95
- PC96
- PC97
- PC98
- PC99
- PC100
weight_decay: 0.0
x_categoricals:
- symbol_id
x_reals:
- PC1
- PC2
- PC3
- PC4
- PC5
- PC6
- PC7
- PC8
- PC9
- PC10
- PC11
- PC12
- PC13
- PC14
- PC15
- PC16
- PC17
- PC18
- PC19
- PC20
- PC21
- PC22
- PC23
- PC24
- PC25
- PC26
- PC27
- PC28
- PC29
- PC30
- PC31
- PC32
- PC33
- PC34
- PC35
- PC36
- PC37
- PC38
- PC39
- PC40
- PC41
- PC42
- PC43
- PC44
- PC45
- PC46
- PC47
- PC48
- PC49
- PC50
- PC51
- PC52
- PC53
- PC54
- PC55
- PC56
- PC57
- PC58
- PC59
- PC60
- PC61
- PC62
- PC63
- PC64
- PC65
- PC66
- PC67
- PC68
- PC69
- PC70
- PC71
- PC72
- PC73
- PC74
- PC75
- PC76
- PC77
- PC78
- PC79
- PC80
- PC81
- PC82
- PC83
- PC84
- PC85
- PC86
- PC87
- PC88
- PC89
- PC90
- PC91
- PC92
- PC93
- PC94
- PC95
- PC96
- PC97
- PC98
- PC99
- PC100
