attention_head_size: 1
categorical_groups: {}
causal_attention: true
dataset_parameters:
  add_encoder_length: false
  add_relative_time_idx: false
  add_target_scales: false
  allow_missing_timesteps: true
  categorical_encoders:
    __group_id__symbol_id: !!python/object:pytorch_forecasting.data.encoders.NaNLabelEncoder
      add_nan: false
      classes_:
        '0': 0
        '1': 1
        '10': 2
        '11': 3
        '12': 4
        '13': 5
        '14': 6
        '15': 7
        '16': 8
        '17': 9
        '18': 10
        '19': 11
        '2': 12
        '20': 13
        '21': 14
        '22': 15
        '23': 16
        '24': 17
        '25': 18
        '26': 19
        '27': 20
        '28': 21
        '29': 22
        '3': 23
        '30': 24
        '31': 25
        '32': 26
        '33': 27
        '34': 28
        '35': 29
        '36': 30
        '37': 31
        '38': 32
        '4': 33
        '5': 34
        '6': 35
        '7': 36
        '8': 37
        '9': 38
      classes_vector_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - &id001 !!python/name:numpy.ndarray ''
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 39
        - !!python/object/apply:numpy.dtype
          args:
          - U2
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - 8
          - 4
          - 8
        - false
        - !!binary |
          MAAAAAAAAAAxAAAAAAAAADEAAAAwAAAAMQAAADEAAAAxAAAAMgAAADEAAAAzAAAAMQAAADQAAAAx
          AAAANQAAADEAAAA2AAAAMQAAADcAAAAxAAAAOAAAADEAAAA5AAAAMgAAAAAAAAAyAAAAMAAAADIA
          AAAxAAAAMgAAADIAAAAyAAAAMwAAADIAAAA0AAAAMgAAADUAAAAyAAAANgAAADIAAAA3AAAAMgAA
          ADgAAAAyAAAAOQAAADMAAAAAAAAAMwAAADAAAAAzAAAAMQAAADMAAAAyAAAAMwAAADMAAAAzAAAA
          NAAAADMAAAA1AAAAMwAAADYAAAAzAAAANwAAADMAAAA4AAAANAAAAAAAAAA1AAAAAAAAADYAAAAA
          AAAANwAAAAAAAAA4AAAAAAAAADkAAAAAAAAA
      warn: true
    symbol_id: !!python/object:pytorch_forecasting.data.encoders.NaNLabelEncoder
      add_nan: true
      classes_: &id003
        '0': 1
        '1': 2
        '10': 3
        '11': 4
        '12': 5
        '13': 6
        '14': 7
        '15': 8
        '16': 9
        '17': 10
        '18': 11
        '19': 12
        '2': 13
        '20': 14
        '21': 15
        '22': 16
        '23': 17
        '24': 18
        '25': 19
        '26': 20
        '27': 21
        '28': 22
        '29': 23
        '3': 24
        '30': 25
        '31': 26
        '32': 27
        '33': 28
        '34': 29
        '35': 30
        '36': 31
        '37': 32
        '38': 33
        '4': 34
        '5': 35
        '6': 36
        '7': 37
        '8': 38
        '9': 39
        nan: 0
      classes_vector_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 40
        - !!python/object/apply:numpy.dtype
          args:
          - U3
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - 12
          - 4
          - 8
        - false
        - !!binary |
          bgAAAGEAAABuAAAAMAAAAAAAAAAAAAAAMQAAAAAAAAAAAAAAMQAAADAAAAAAAAAAMQAAADEAAAAA
          AAAAMQAAADIAAAAAAAAAMQAAADMAAAAAAAAAMQAAADQAAAAAAAAAMQAAADUAAAAAAAAAMQAAADYA
          AAAAAAAAMQAAADcAAAAAAAAAMQAAADgAAAAAAAAAMQAAADkAAAAAAAAAMgAAAAAAAAAAAAAAMgAA
          ADAAAAAAAAAAMgAAADEAAAAAAAAAMgAAADIAAAAAAAAAMgAAADMAAAAAAAAAMgAAADQAAAAAAAAA
          MgAAADUAAAAAAAAAMgAAADYAAAAAAAAAMgAAADcAAAAAAAAAMgAAADgAAAAAAAAAMgAAADkAAAAA
          AAAAMwAAAAAAAAAAAAAAMwAAADAAAAAAAAAAMwAAADEAAAAAAAAAMwAAADIAAAAAAAAAMwAAADMA
          AAAAAAAAMwAAADQAAAAAAAAAMwAAADUAAAAAAAAAMwAAADYAAAAAAAAAMwAAADcAAAAAAAAAMwAA
          ADgAAAAAAAAANAAAAAAAAAAAAAAANQAAAAAAAAAAAAAANgAAAAAAAAAAAAAANwAAAAAAAAAAAAAA
          OAAAAAAAAAAAAAAAOQAAAAAAAAAAAAAA
      warn: true
  constant_fill_strategy: null
  group_ids:
  - symbol_id
  lags: null
  max_encoder_length: 50
  max_prediction_length: 1
  min_encoder_length: 50
  min_prediction_idx: !!python/object/apply:numpy._core.multiarray.scalar
  - !!python/object/apply:numpy.dtype
    args:
    - i8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    AAAAAAAAAAA=
  min_prediction_length: 1
  predict_mode: false
  randomize_length: null
  scalers:
    feature_00_z: null
    feature_01_z: null
    feature_02_z: null
    feature_03_z: null
    feature_04_z: null
    feature_05_z: null
    feature_06_z: null
    feature_07_z: null
    feature_08_z: null
    feature_09_z: null
    feature_10_z: null
    feature_11_z: null
    feature_12_z: null
    feature_13_z: null
    feature_14_z: null
    feature_15_z: null
    feature_16_z: null
    feature_17_z: null
    feature_18_z: null
    feature_19_z: null
    feature_20_z: null
    feature_21_z: null
    feature_22_z: null
    feature_23_z: null
    feature_24_z: null
    feature_25_z: null
    feature_26_z: null
    feature_27_z: null
    feature_28_z: null
    feature_29_z: null
    feature_30_z: null
    feature_31_z: null
    feature_32_z: null
    feature_33_z: null
    feature_34_z: null
    feature_35_z: null
    feature_36_z: null
    feature_37_z: null
    feature_38_z: null
    feature_39_z: null
    feature_40_z: null
    feature_41_z: null
    feature_42_z: null
    feature_43_z: null
    feature_44_z: null
    feature_45_z: null
    feature_46_z: null
    feature_47_z: null
    feature_48_z: null
    feature_49_z: null
    feature_50_z: null
    feature_51_z: null
    feature_52_z: null
    feature_53_z: null
    feature_54_z: null
    feature_55_z: null
    feature_56_z: null
    feature_57_z: null
    feature_58_z: null
    feature_59_z: null
    feature_60_z: null
    feature_61_z: null
    feature_62_z: null
    feature_63_z: null
    feature_64_z: null
    feature_65_z: null
    feature_66_z: null
    feature_67_z: null
    feature_68_z: null
    feature_69_z: null
    feature_70_z: null
    feature_71_z: null
    feature_72_z: null
    feature_73_z: null
    feature_74_z: null
    feature_75_z: null
    feature_76_z: null
    feature_77_z: null
    feature_78_z: null
    time_bucket: null
  static_categoricals:
  - symbol_id
  static_reals: null
  target: responder_6
  target_normalizer: &id004 !!python/object:pytorch_forecasting.data.encoders.TorchNormalizer
    _method_kwargs: {}
    center: true
    center_: !!python/object/apply:numpy._core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple
        - 0
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple []
      - &id002 !!python/object/apply:numpy.dtype
        args:
        - f4
        - false
        - true
        state: !!python/tuple
        - 3
        - <
        - null
        - null
        - null
        - -1
        - -1
        - 0
      - false
      - !!binary |
        AAAAAA==
    method: identity
    method_kwargs: null
    scale_: !!python/object/apply:numpy._core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple
        - 0
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple []
      - *id002
      - false
      - !!binary |
        AACAPw==
    transformation: null
  time_idx: time_idx
  time_varying_known_categoricals: null
  time_varying_known_reals:
  - time_bucket
  - feature_00_z
  - feature_01_z
  - feature_02_z
  - feature_03_z
  - feature_04_z
  - feature_05_z
  - feature_06_z
  - feature_07_z
  - feature_08_z
  - feature_09_z
  - feature_10_z
  - feature_11_z
  - feature_12_z
  - feature_13_z
  - feature_14_z
  - feature_15_z
  - feature_16_z
  - feature_17_z
  - feature_18_z
  - feature_19_z
  - feature_20_z
  - feature_21_z
  - feature_22_z
  - feature_23_z
  - feature_24_z
  - feature_25_z
  - feature_26_z
  - feature_27_z
  - feature_28_z
  - feature_29_z
  - feature_30_z
  - feature_31_z
  - feature_32_z
  - feature_33_z
  - feature_34_z
  - feature_35_z
  - feature_36_z
  - feature_37_z
  - feature_38_z
  - feature_39_z
  - feature_40_z
  - feature_41_z
  - feature_42_z
  - feature_43_z
  - feature_44_z
  - feature_45_z
  - feature_46_z
  - feature_47_z
  - feature_48_z
  - feature_49_z
  - feature_50_z
  - feature_51_z
  - feature_52_z
  - feature_53_z
  - feature_54_z
  - feature_55_z
  - feature_56_z
  - feature_57_z
  - feature_58_z
  - feature_59_z
  - feature_60_z
  - feature_61_z
  - feature_62_z
  - feature_63_z
  - feature_64_z
  - feature_65_z
  - feature_66_z
  - feature_67_z
  - feature_68_z
  - feature_69_z
  - feature_70_z
  - feature_71_z
  - feature_72_z
  - feature_73_z
  - feature_74_z
  - feature_75_z
  - feature_76_z
  - feature_77_z
  - feature_78_z
  time_varying_unknown_categoricals: null
  time_varying_unknown_reals: null
  variable_groups: null
  weight: weight
dropout: 0.1
embedding_labels:
  symbol_id: *id003
embedding_paddings:
- symbol_id
embedding_sizes:
  symbol_id: !!python/tuple
  - 40
  - 13
hidden_continuous_size: 8
hidden_continuous_sizes: {}
hidden_size: 16
learning_rate: 0.001
log_gradient_flow: false
log_interval: 300
log_val_interval: 300
lstm_layers: 1
mask_bias: -1000000000.0
max_encoder_length: 50
monotone_constaints: {}
monotone_constraints: {}
optimizer: !!python/name:torch.optim.adam.Adam ''
optimizer_params: null
output_size: 1
output_transformer: *id004
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 4
reduce_on_plateau_reduction: 2.0
share_single_variable_networks: false
static_categoricals:
- symbol_id
static_reals: []
time_varying_categoricals_decoder: []
time_varying_categoricals_encoder: []
time_varying_reals_decoder:
- time_bucket
- feature_00_z
- feature_01_z
- feature_02_z
- feature_03_z
- feature_04_z
- feature_05_z
- feature_06_z
- feature_07_z
- feature_08_z
- feature_09_z
- feature_10_z
- feature_11_z
- feature_12_z
- feature_13_z
- feature_14_z
- feature_15_z
- feature_16_z
- feature_17_z
- feature_18_z
- feature_19_z
- feature_20_z
- feature_21_z
- feature_22_z
- feature_23_z
- feature_24_z
- feature_25_z
- feature_26_z
- feature_27_z
- feature_28_z
- feature_29_z
- feature_30_z
- feature_31_z
- feature_32_z
- feature_33_z
- feature_34_z
- feature_35_z
- feature_36_z
- feature_37_z
- feature_38_z
- feature_39_z
- feature_40_z
- feature_41_z
- feature_42_z
- feature_43_z
- feature_44_z
- feature_45_z
- feature_46_z
- feature_47_z
- feature_48_z
- feature_49_z
- feature_50_z
- feature_51_z
- feature_52_z
- feature_53_z
- feature_54_z
- feature_55_z
- feature_56_z
- feature_57_z
- feature_58_z
- feature_59_z
- feature_60_z
- feature_61_z
- feature_62_z
- feature_63_z
- feature_64_z
- feature_65_z
- feature_66_z
- feature_67_z
- feature_68_z
- feature_69_z
- feature_70_z
- feature_71_z
- feature_72_z
- feature_73_z
- feature_74_z
- feature_75_z
- feature_76_z
- feature_77_z
- feature_78_z
time_varying_reals_encoder:
- time_bucket
- feature_00_z
- feature_01_z
- feature_02_z
- feature_03_z
- feature_04_z
- feature_05_z
- feature_06_z
- feature_07_z
- feature_08_z
- feature_09_z
- feature_10_z
- feature_11_z
- feature_12_z
- feature_13_z
- feature_14_z
- feature_15_z
- feature_16_z
- feature_17_z
- feature_18_z
- feature_19_z
- feature_20_z
- feature_21_z
- feature_22_z
- feature_23_z
- feature_24_z
- feature_25_z
- feature_26_z
- feature_27_z
- feature_28_z
- feature_29_z
- feature_30_z
- feature_31_z
- feature_32_z
- feature_33_z
- feature_34_z
- feature_35_z
- feature_36_z
- feature_37_z
- feature_38_z
- feature_39_z
- feature_40_z
- feature_41_z
- feature_42_z
- feature_43_z
- feature_44_z
- feature_45_z
- feature_46_z
- feature_47_z
- feature_48_z
- feature_49_z
- feature_50_z
- feature_51_z
- feature_52_z
- feature_53_z
- feature_54_z
- feature_55_z
- feature_56_z
- feature_57_z
- feature_58_z
- feature_59_z
- feature_60_z
- feature_61_z
- feature_62_z
- feature_63_z
- feature_64_z
- feature_65_z
- feature_66_z
- feature_67_z
- feature_68_z
- feature_69_z
- feature_70_z
- feature_71_z
- feature_72_z
- feature_73_z
- feature_74_z
- feature_75_z
- feature_76_z
- feature_77_z
- feature_78_z
weight_decay: 0.0
x_categoricals:
- symbol_id
x_reals:
- time_bucket
- feature_00_z
- feature_01_z
- feature_02_z
- feature_03_z
- feature_04_z
- feature_05_z
- feature_06_z
- feature_07_z
- feature_08_z
- feature_09_z
- feature_10_z
- feature_11_z
- feature_12_z
- feature_13_z
- feature_14_z
- feature_15_z
- feature_16_z
- feature_17_z
- feature_18_z
- feature_19_z
- feature_20_z
- feature_21_z
- feature_22_z
- feature_23_z
- feature_24_z
- feature_25_z
- feature_26_z
- feature_27_z
- feature_28_z
- feature_29_z
- feature_30_z
- feature_31_z
- feature_32_z
- feature_33_z
- feature_34_z
- feature_35_z
- feature_36_z
- feature_37_z
- feature_38_z
- feature_39_z
- feature_40_z
- feature_41_z
- feature_42_z
- feature_43_z
- feature_44_z
- feature_45_z
- feature_46_z
- feature_47_z
- feature_48_z
- feature_49_z
- feature_50_z
- feature_51_z
- feature_52_z
- feature_53_z
- feature_54_z
- feature_55_z
- feature_56_z
- feature_57_z
- feature_58_z
- feature_59_z
- feature_60_z
- feature_61_z
- feature_62_z
- feature_63_z
- feature_64_z
- feature_65_z
- feature_66_z
- feature_67_z
- feature_68_z
- feature_69_z
- feature_70_z
- feature_71_z
- feature_72_z
- feature_73_z
- feature_74_z
- feature_75_z
- feature_76_z
- feature_77_z
- feature_78_z
