attention_head_size: 1
categorical_groups: {}
causal_attention: true
dataset_parameters:
  add_encoder_length: false
  add_relative_time_idx: false
  add_target_scales: false
  allow_missing_timesteps: true
  categorical_encoders:
    __group_id__symbol_id: !!python/object:pytorch_forecasting.data.encoders.NaNLabelEncoder
      add_nan: false
      classes_:
        '0': 0
        '1': 1
        '10': 2
        '11': 3
        '12': 4
        '13': 5
        '14': 6
        '15': 7
        '16': 8
        '17': 9
        '18': 10
        '19': 11
        '2': 12
        '20': 13
        '21': 14
        '22': 15
        '23': 16
        '24': 17
        '25': 18
        '26': 19
        '27': 20
        '28': 21
        '29': 22
        '3': 23
        '30': 24
        '31': 25
        '32': 26
        '33': 27
        '34': 28
        '35': 29
        '36': 30
        '37': 31
        '38': 32
        '4': 33
        '5': 34
        '6': 35
        '7': 36
        '8': 37
        '9': 38
      classes_vector_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - &id001 !!python/name:numpy.ndarray ''
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 39
        - !!python/object/apply:numpy.dtype
          args:
          - U2
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - 8
          - 4
          - 8
        - false
        - !!binary |
          MAAAAAAAAAAxAAAAAAAAADEAAAAwAAAAMQAAADEAAAAxAAAAMgAAADEAAAAzAAAAMQAAADQAAAAx
          AAAANQAAADEAAAA2AAAAMQAAADcAAAAxAAAAOAAAADEAAAA5AAAAMgAAAAAAAAAyAAAAMAAAADIA
          AAAxAAAAMgAAADIAAAAyAAAAMwAAADIAAAA0AAAAMgAAADUAAAAyAAAANgAAADIAAAA3AAAAMgAA
          ADgAAAAyAAAAOQAAADMAAAAAAAAAMwAAADAAAAAzAAAAMQAAADMAAAAyAAAAMwAAADMAAAAzAAAA
          NAAAADMAAAA1AAAAMwAAADYAAAAzAAAANwAAADMAAAA4AAAANAAAAAAAAAA1AAAAAAAAADYAAAAA
          AAAANwAAAAAAAAA4AAAAAAAAADkAAAAAAAAA
      warn: true
    gap_flag: !!python/object:pytorch_forecasting.data.encoders.NaNLabelEncoder
      add_nan: false
      classes_: &id003
        'False': 0
        'True': 1
      classes_vector_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 2
        - !!python/object/apply:numpy.dtype
          args:
          - U5
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - 20
          - 4
          - 8
        - false
        - !!binary |
          RgAAAGEAAABsAAAAcwAAAGUAAABUAAAAcgAAAHUAAABlAAAAAAAAAA==
      warn: true
    time_bucket: !!python/object:pytorch_forecasting.data.encoders.NaNLabelEncoder
      add_nan: false
      classes_: &id004
        '0': 0
        '1': 1
        '2': 2
        '3': 3
        '4': 4
        '5': 5
      classes_vector_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 6
        - !!python/object/apply:numpy.dtype
          args:
          - U1
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - 4
          - 4
          - 8
        - false
        - !!binary |
          MAAAADEAAAAyAAAAMwAAADQAAAA1AAAA
      warn: true
  constant_fill_strategy: null
  group_ids:
  - symbol_id
  lags: null
  max_encoder_length: 10
  max_prediction_length: 1
  min_encoder_length: 5
  min_prediction_idx: !!python/object/apply:numpy._core.multiarray.scalar
  - !!python/object/apply:numpy.dtype
    args:
    - i8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    AAAAAAAAAAA=
  min_prediction_length: 1
  predict_mode: false
  randomize_length: null
  scalers:
    feature_09: null
    feature_26__csrank: null
    feature_59__cs_z: null
    feature_60__cs_z: null
    feature_60__csrank: null
    time_cos: null
    time_pos: null
    time_sin: null
    z_feature_01__ewm50: null
    z_feature_04: null
    z_feature_04__ewm10: null
    z_feature_04__ewm5: null
    z_feature_04__ewm50: null
    z_feature_05__ewm50: null
    z_feature_05__rmean30: null
    z_feature_05__rstd30: null
    z_feature_06: null
    z_feature_06__ewm10: null
    z_feature_06__rmean14: null
    z_feature_06__rz30: null
    z_feature_07: null
    z_feature_07__rmean3: null
    z_feature_07__rmean30: null
    z_feature_08__ewm50: null
    z_feature_08__lag100: null
    z_feature_08__rmean30: null
    z_feature_20__diff50: null
    z_feature_21__diff50: null
    z_feature_21__lag900: null
    z_feature_21__ret50: null
    z_feature_22__diff50: null
    z_feature_23__diff50: null
    z_feature_23__ret50: null
    z_feature_24: null
    z_feature_24__diff50: null
    z_feature_24__lag4840: null
    z_feature_25__diff50: null
    z_feature_25__ret50: null
    z_feature_26__diff50: null
    z_feature_26__lag6776: null
    z_feature_26__lag900: null
    z_feature_27__ret50: null
    z_feature_30__diff50: null
    z_feature_30__lag3872: null
    z_feature_30__lag50: null
    z_feature_30__lag968: null
    z_feature_31__diff50: null
    z_feature_31__lag1936: null
    z_feature_31__lag4840: null
    z_feature_31__ret50: null
    z_feature_33__rmean3: null
    z_feature_36: null
    z_feature_37__rstd30: null
    z_feature_38__ewm50: null
    z_feature_38__lag100: null
    z_feature_40__ewm10: null
    z_feature_42__ewm50: null
    z_feature_42__rmean30: null
    z_feature_43__ewm50: null
    z_feature_45__ewm5: null
    z_feature_47__rstd30: null
    z_feature_48: null
    z_feature_51__ewm10: null
    z_feature_51__ewm50: null
    z_feature_51__rmean14: null
    z_feature_52__rstd30: null
    z_feature_53__ewm50: null
    z_feature_54__ewm10: null
    z_feature_54__rmean14: null
    z_feature_55__ewm50: null
    z_feature_58: null
    z_feature_58__ewm50: null
    z_feature_59: null
    z_feature_59__ewm5: null
    z_feature_59__ewm50: null
    z_feature_59__rstd14: null
    z_feature_59__rstd30: null
    z_feature_60__rstd30: null
    z_feature_61__diff50: null
    z_feature_61__lag1936: null
    z_feature_61__lag2904: null
    z_feature_61__lag3872: null
    z_feature_61__lag4840: null
    z_feature_61__lag500: null
    z_feature_61__lag5808: null
    z_feature_61__lag6776: null
    z_feature_61__lag7744: null
    z_feature_61__lag900: null
    z_feature_61__ret50: null
    z_feature_68__ewm10: null
    z_feature_75__rstd3: null
    z_feature_75__rstd7: null
    z_feature_76__rstd14: null
    z_responder_2_prev_tail_lag10: null
    z_responder_3_prevday_std: null
    z_responder_5_prevday_mean: null
    z_responder_6_prev_tail_lag50: null
    z_responder_6_prev_tail_lag967: null
    z_responder_6_prevday_std: null
    z_responder_7_close_roll14_std: null
    z_responder_7_prev_tail_lag967: null
    z_responder_8_prev_tail_lag967: null
    z_responder_8_prevday_mean: null
  static_categoricals: []
  static_reals: []
  target: responder_6
  target_normalizer: &id005 !!python/object:pytorch_forecasting.data.encoders.TorchNormalizer
    _method_kwargs: {}
    center: true
    center_: !!python/object/apply:numpy._core.multiarray.scalar
    - &id002 !!python/object/apply:numpy.dtype
      args:
      - f4
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - !!binary |
      t/P6OQ==
    method: standard
    method_kwargs: null
    scale_: !!python/object/apply:numpy._core.multiarray.scalar
    - *id002
    - !!binary |
      9jxQPw==
    transformation: null
  time_idx: time_idx
  time_varying_known_categoricals:
  - time_bucket
  - gap_flag
  time_varying_known_reals:
  - time_pos
  - time_sin
  - time_cos
  - feature_09
  - feature_60__csrank
  - feature_26__csrank
  - feature_60__cs_z
  - feature_59__cs_z
  - z_feature_06
  - z_feature_36
  - z_feature_04
  - z_feature_59__rstd30
  - z_feature_07
  - z_feature_61__ret50
  - z_feature_31__lag4840
  - z_feature_61__lag7744
  - z_feature_61__diff50
  - z_feature_51__ewm10
  - z_feature_61__lag1936
  - z_feature_59__ewm5
  - z_feature_48
  - z_feature_61__lag900
  - z_feature_59
  - z_feature_51__rmean14
  - z_feature_31__diff50
  - z_feature_04__ewm5
  - z_feature_61__lag3872
  - z_feature_04__ewm10
  - z_feature_06__rz30
  - z_feature_60__rstd30
  - z_feature_54__ewm10
  - z_feature_37__rstd30
  - z_feature_22__diff50
  - z_feature_30__lag50
  - z_feature_01__ewm50
  - z_feature_61__lag4840
  - z_feature_61__lag2904
  - z_responder_2_prev_tail_lag10
  - z_feature_26__lag900
  - z_feature_08__ewm50
  - z_feature_20__diff50
  - z_feature_04__ewm50
  - z_responder_5_prevday_mean
  - z_feature_31__lag1936
  - z_feature_75__rstd7
  - z_feature_58__ewm50
  - z_feature_43__ewm50
  - z_feature_25__diff50
  - z_feature_30__lag968
  - z_feature_40__ewm10
  - z_responder_7_close_roll14_std
  - z_responder_8_prevday_mean
  - z_feature_61__lag6776
  - z_responder_7_prev_tail_lag967
  - z_responder_6_prevday_std
  - z_feature_38__lag100
  - z_feature_26__diff50
  - z_feature_76__rstd14
  - z_feature_55__ewm50
  - z_feature_52__rstd30
  - z_feature_61__lag5808
  - z_responder_3_prevday_std
  - z_feature_26__lag6776
  - z_feature_06__ewm10
  - z_responder_8_prev_tail_lag967
  - z_feature_07__rmean3
  - z_feature_75__rstd3
  - z_feature_08__rmean30
  - z_feature_08__lag100
  - z_feature_30__diff50
  - z_feature_25__ret50
  - z_feature_42__rmean30
  - z_feature_21__diff50
  - z_feature_59__ewm50
  - z_responder_6_prev_tail_lag967
  - z_feature_07__rmean30
  - z_feature_24__lag4840
  - z_feature_38__ewm50
  - z_feature_68__ewm10
  - z_feature_30__lag3872
  - z_feature_05__rstd30
  - z_feature_42__ewm50
  - z_feature_45__ewm5
  - z_feature_24__diff50
  - z_feature_31__ret50
  - z_feature_05__rmean30
  - z_feature_23__diff50
  - z_responder_6_prev_tail_lag50
  - z_feature_59__rstd14
  - z_feature_21__lag900
  - z_feature_06__rmean14
  - z_feature_21__ret50
  - z_feature_54__rmean14
  - z_feature_05__ewm50
  - z_feature_23__ret50
  - z_feature_58
  - z_feature_53__ewm50
  - z_feature_24
  - z_feature_47__rstd30
  - z_feature_33__rmean3
  - z_feature_61__lag500
  - z_feature_27__ret50
  - z_feature_51__ewm50
  time_varying_unknown_categoricals: []
  time_varying_unknown_reals: []
  variable_groups: null
  weight: weight
dropout: 0.3
embedding_labels:
  gap_flag: *id003
  time_bucket: *id004
embedding_paddings: []
embedding_sizes:
  gap_flag: !!python/tuple
  - 2
  - 1
  time_bucket: !!python/tuple
  - 6
  - 4
hidden_continuous_size: 32
hidden_continuous_sizes: {}
hidden_size: 64
learning_rate: 0.002
log_gradient_flow: false
log_interval: -1
log_val_interval: null
logging_metrics: []
lstm_layers: 1
mask_bias: -1000000000.0
max_encoder_length: 10
monotone_constaints: {}
monotone_constraints: {}
optimizer: !!python/name:torch.optim.adamw.AdamW ''
optimizer_params:
  weight_decay: 0.0001
output_size: 1
output_transformer: *id005
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 3
reduce_on_plateau_reduction: 2.0
share_single_variable_networks: false
static_categoricals: []
static_reals: []
time_varying_categoricals_decoder:
- time_bucket
- gap_flag
time_varying_categoricals_encoder:
- time_bucket
- gap_flag
time_varying_reals_decoder:
- time_pos
- time_sin
- time_cos
- feature_09
- feature_60__csrank
- feature_26__csrank
- feature_60__cs_z
- feature_59__cs_z
- z_feature_06
- z_feature_36
- z_feature_04
- z_feature_59__rstd30
- z_feature_07
- z_feature_61__ret50
- z_feature_31__lag4840
- z_feature_61__lag7744
- z_feature_61__diff50
- z_feature_51__ewm10
- z_feature_61__lag1936
- z_feature_59__ewm5
- z_feature_48
- z_feature_61__lag900
- z_feature_59
- z_feature_51__rmean14
- z_feature_31__diff50
- z_feature_04__ewm5
- z_feature_61__lag3872
- z_feature_04__ewm10
- z_feature_06__rz30
- z_feature_60__rstd30
- z_feature_54__ewm10
- z_feature_37__rstd30
- z_feature_22__diff50
- z_feature_30__lag50
- z_feature_01__ewm50
- z_feature_61__lag4840
- z_feature_61__lag2904
- z_responder_2_prev_tail_lag10
- z_feature_26__lag900
- z_feature_08__ewm50
- z_feature_20__diff50
- z_feature_04__ewm50
- z_responder_5_prevday_mean
- z_feature_31__lag1936
- z_feature_75__rstd7
- z_feature_58__ewm50
- z_feature_43__ewm50
- z_feature_25__diff50
- z_feature_30__lag968
- z_feature_40__ewm10
- z_responder_7_close_roll14_std
- z_responder_8_prevday_mean
- z_feature_61__lag6776
- z_responder_7_prev_tail_lag967
- z_responder_6_prevday_std
- z_feature_38__lag100
- z_feature_26__diff50
- z_feature_76__rstd14
- z_feature_55__ewm50
- z_feature_52__rstd30
- z_feature_61__lag5808
- z_responder_3_prevday_std
- z_feature_26__lag6776
- z_feature_06__ewm10
- z_responder_8_prev_tail_lag967
- z_feature_07__rmean3
- z_feature_75__rstd3
- z_feature_08__rmean30
- z_feature_08__lag100
- z_feature_30__diff50
- z_feature_25__ret50
- z_feature_42__rmean30
- z_feature_21__diff50
- z_feature_59__ewm50
- z_responder_6_prev_tail_lag967
- z_feature_07__rmean30
- z_feature_24__lag4840
- z_feature_38__ewm50
- z_feature_68__ewm10
- z_feature_30__lag3872
- z_feature_05__rstd30
- z_feature_42__ewm50
- z_feature_45__ewm5
- z_feature_24__diff50
- z_feature_31__ret50
- z_feature_05__rmean30
- z_feature_23__diff50
- z_responder_6_prev_tail_lag50
- z_feature_59__rstd14
- z_feature_21__lag900
- z_feature_06__rmean14
- z_feature_21__ret50
- z_feature_54__rmean14
- z_feature_05__ewm50
- z_feature_23__ret50
- z_feature_58
- z_feature_53__ewm50
- z_feature_24
- z_feature_47__rstd30
- z_feature_33__rmean3
- z_feature_61__lag500
- z_feature_27__ret50
- z_feature_51__ewm50
time_varying_reals_encoder:
- time_pos
- time_sin
- time_cos
- feature_09
- feature_60__csrank
- feature_26__csrank
- feature_60__cs_z
- feature_59__cs_z
- z_feature_06
- z_feature_36
- z_feature_04
- z_feature_59__rstd30
- z_feature_07
- z_feature_61__ret50
- z_feature_31__lag4840
- z_feature_61__lag7744
- z_feature_61__diff50
- z_feature_51__ewm10
- z_feature_61__lag1936
- z_feature_59__ewm5
- z_feature_48
- z_feature_61__lag900
- z_feature_59
- z_feature_51__rmean14
- z_feature_31__diff50
- z_feature_04__ewm5
- z_feature_61__lag3872
- z_feature_04__ewm10
- z_feature_06__rz30
- z_feature_60__rstd30
- z_feature_54__ewm10
- z_feature_37__rstd30
- z_feature_22__diff50
- z_feature_30__lag50
- z_feature_01__ewm50
- z_feature_61__lag4840
- z_feature_61__lag2904
- z_responder_2_prev_tail_lag10
- z_feature_26__lag900
- z_feature_08__ewm50
- z_feature_20__diff50
- z_feature_04__ewm50
- z_responder_5_prevday_mean
- z_feature_31__lag1936
- z_feature_75__rstd7
- z_feature_58__ewm50
- z_feature_43__ewm50
- z_feature_25__diff50
- z_feature_30__lag968
- z_feature_40__ewm10
- z_responder_7_close_roll14_std
- z_responder_8_prevday_mean
- z_feature_61__lag6776
- z_responder_7_prev_tail_lag967
- z_responder_6_prevday_std
- z_feature_38__lag100
- z_feature_26__diff50
- z_feature_76__rstd14
- z_feature_55__ewm50
- z_feature_52__rstd30
- z_feature_61__lag5808
- z_responder_3_prevday_std
- z_feature_26__lag6776
- z_feature_06__ewm10
- z_responder_8_prev_tail_lag967
- z_feature_07__rmean3
- z_feature_75__rstd3
- z_feature_08__rmean30
- z_feature_08__lag100
- z_feature_30__diff50
- z_feature_25__ret50
- z_feature_42__rmean30
- z_feature_21__diff50
- z_feature_59__ewm50
- z_responder_6_prev_tail_lag967
- z_feature_07__rmean30
- z_feature_24__lag4840
- z_feature_38__ewm50
- z_feature_68__ewm10
- z_feature_30__lag3872
- z_feature_05__rstd30
- z_feature_42__ewm50
- z_feature_45__ewm5
- z_feature_24__diff50
- z_feature_31__ret50
- z_feature_05__rmean30
- z_feature_23__diff50
- z_responder_6_prev_tail_lag50
- z_feature_59__rstd14
- z_feature_21__lag900
- z_feature_06__rmean14
- z_feature_21__ret50
- z_feature_54__rmean14
- z_feature_05__ewm50
- z_feature_23__ret50
- z_feature_58
- z_feature_53__ewm50
- z_feature_24
- z_feature_47__rstd30
- z_feature_33__rmean3
- z_feature_61__lag500
- z_feature_27__ret50
- z_feature_51__ewm50
weight_decay: 0.0
x_categoricals:
- time_bucket
- gap_flag
x_reals:
- time_pos
- time_sin
- time_cos
- feature_09
- feature_60__csrank
- feature_26__csrank
- feature_60__cs_z
- feature_59__cs_z
- z_feature_06
- z_feature_36
- z_feature_04
- z_feature_59__rstd30
- z_feature_07
- z_feature_61__ret50
- z_feature_31__lag4840
- z_feature_61__lag7744
- z_feature_61__diff50
- z_feature_51__ewm10
- z_feature_61__lag1936
- z_feature_59__ewm5
- z_feature_48
- z_feature_61__lag900
- z_feature_59
- z_feature_51__rmean14
- z_feature_31__diff50
- z_feature_04__ewm5
- z_feature_61__lag3872
- z_feature_04__ewm10
- z_feature_06__rz30
- z_feature_60__rstd30
- z_feature_54__ewm10
- z_feature_37__rstd30
- z_feature_22__diff50
- z_feature_30__lag50
- z_feature_01__ewm50
- z_feature_61__lag4840
- z_feature_61__lag2904
- z_responder_2_prev_tail_lag10
- z_feature_26__lag900
- z_feature_08__ewm50
- z_feature_20__diff50
- z_feature_04__ewm50
- z_responder_5_prevday_mean
- z_feature_31__lag1936
- z_feature_75__rstd7
- z_feature_58__ewm50
- z_feature_43__ewm50
- z_feature_25__diff50
- z_feature_30__lag968
- z_feature_40__ewm10
- z_responder_7_close_roll14_std
- z_responder_8_prevday_mean
- z_feature_61__lag6776
- z_responder_7_prev_tail_lag967
- z_responder_6_prevday_std
- z_feature_38__lag100
- z_feature_26__diff50
- z_feature_76__rstd14
- z_feature_55__ewm50
- z_feature_52__rstd30
- z_feature_61__lag5808
- z_responder_3_prevday_std
- z_feature_26__lag6776
- z_feature_06__ewm10
- z_responder_8_prev_tail_lag967
- z_feature_07__rmean3
- z_feature_75__rstd3
- z_feature_08__rmean30
- z_feature_08__lag100
- z_feature_30__diff50
- z_feature_25__ret50
- z_feature_42__rmean30
- z_feature_21__diff50
- z_feature_59__ewm50
- z_responder_6_prev_tail_lag967
- z_feature_07__rmean30
- z_feature_24__lag4840
- z_feature_38__ewm50
- z_feature_68__ewm10
- z_feature_30__lag3872
- z_feature_05__rstd30
- z_feature_42__ewm50
- z_feature_45__ewm5
- z_feature_24__diff50
- z_feature_31__ret50
- z_feature_05__rmean30
- z_feature_23__diff50
- z_responder_6_prev_tail_lag50
- z_feature_59__rstd14
- z_feature_21__lag900
- z_feature_06__rmean14
- z_feature_21__ret50
- z_feature_54__rmean14
- z_feature_05__ewm50
- z_feature_23__ret50
- z_feature_58
- z_feature_53__ewm50
- z_feature_24
- z_feature_47__rstd30
- z_feature_33__rmean3
- z_feature_61__lag500
- z_feature_27__ret50
- z_feature_51__ewm50
